[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GeneralAstrodynamics = "8068df5b-8501-4530-bd82-d24d3c9619db"
Geodesics = "6aaf26a4-c633-11e8-35ae-8904cb805353"
Orbits = "88f3d70c-3a4c-11ed-1389-4902f2e49de8"
PlanetOrbits = "fd6f9641-d78f-43ce-a379-ceb0bddb468a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
SatelliteToolboxSgp4 = "ba14ac17-bfc9-4710-a76f-b32930ef2339"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"
